version: '3'
services:
    flask_app_project:
        build:
            context: .
            dockerfile: dashboard/Dockerfile_dashboard  # Specify the unique Dockerfile name
        ports:
            - 8080:5000
        volumes:
            - ./data:/data
        environment:
            - NAME=Flask-App
            - PYTHONPATH=/app
        working_dir: /app
        develop: 
            watch:
                - action: sync+restart
                  path: ./dashboard/
                  target: /app
                - action: rebuild
                  path: ./dashboard/requirements.txt
                  target: /app
        depends_on:
            db_dashboard_project:
                condition: service_healthy
    
    jupyter_project:
        build:
            context: .
            dockerfile: notebook/Dockerfile_notebook
        ports:
            - 8888:8888
        volumes:
            - ./notebook:/notebook
            - ./data:/data
        environment:
            - JUPYTER_ENABLE_LAB=yes
            - NB_USER=infomdss
            - CHOWN_HOME=yes
        working_dir: /notebook
    
    db_dashboard_project:
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=student
            - POSTGRES_PASSWORD=infomdss
            - POSTGRES_DB=dashboard
        volumes:
            - db_dashboard-data:/var/lib/postgresql/data/
        container_name: db_dashboard_project
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
            interval: 3s
            timeout: 60s
            retries: 10
            start_period: 80s

volumes:
    db_dashboard-data:
