# stage 1: Build the react application
FROM node:22-alpine AS build

ARG VITE_BACKEND_BASE_URL=http://127.0.0.1:8083

WORKDIR /app-build

# Copy source files
COPY . .

# Install required node packages
RUN npm ci

# Build the react application
RUN VITE_BACKEND_BASE_URL=$VITE_BACKEND_BASE_URL npm run build

# Stage 2: serve react application with nignx
FROM nginx:alpine

# Copy file from build container
COPY --from=build /app-build/dist /usr/share/nginx/html

# Configure nginx with custom nginx file
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80 for the server
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]